name: melos_git_diff_issue
sdkPath: .fvm/flutter_sdk
packages:
  - apps/sample_app
  - packages/*

scripts:
  test-filter:
    name: test filter
    run: basename $(pwd)
    exec:
      concurrency: 5
    packageFilters:
      diff: HEAD
